spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/blog-app
    name: exam_portal
    password: btiger
  jpa:
    properties:
      hibernate:
        fromat_sql: 'true'
        dialect: org.hibernate.dialect.MariaDB102Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
